version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run:
          name: Install Wine64 (Needed for windows build)
          command: | 
            sudo apt-get update
            sudo apt install wine64 zip
      - run:
          name: add access token for github npm registry
          command: echo "//npm.pkg.github.com/:_authToken=$GH_NPM_TOKEN" >> ./frontend/.npmrc
      - run:
          name: Install Dependencies (electron)
          command: npm install
      - run:
          name: Install Dependencies (react)
          command: cd frontend && npm install
      - run:
          name: Generate Builds
          command: npm run release:cross
      - run:
          name: Archive Windows release directory
          command: zip -r windows-release.zip release/tray-electron-win32-x64/
      - run:
          name: Archive macOS release directory
          command: zip -r macos-release.zip release/tray-electron-darwin-x64/

      - store_artifacts:
          path: ~/repo/windows-release.zip
          destination: crc-tray-electron-windows
      - store_artifacts:
          path: ~/repo/macos-release.zip
          destination: crc-tray-electron-macos
